node {
    stage ("Checkout DataService"){
        git branch: 'master', url: ' https://github.com/imcbee/Team1-JavaJive.git'
    }
    
    stage ("Gradle Build - DataService") {
	
		sh 'pwd'
		sh 'cd MCCTeam1JavaJive/ && gradle clean build' // replace all bat into sh for linux systems

    }
    
    stage ("Gradle Bootjar-Package - DataService") {
        sh 'cd MCCTeam1JavaJive/ && gradle bootjar'
    }
    
    stage ("Containerize the app-docker build - DataApi") {
        sh 'docker build --rm -t dataapi:v1.0 -f MCCTeam1JavaJive/Dockerfile ./MCCTeam1JavaJive'
    }
    
    stage ("Inspect the docker image - DataApi"){
        sh "docker images dataapi:v1.0"
        sh "docker inspect dataapi:v1.0"
    }
    
    stage ("Run Docker container instance - DataApi"){
    	sh "docker ps -a"
        sh "docker run -d --rm --name dataapi -p 8080:8080 dataapi:v1.0"
        sh "docker ps -a"
        
     }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {

	    stage('Release- DataService') {
		 sh "docker stop dataapi"
	     sh 'echo MCC DataService is ready to release!'

	    }
	  }
    }
}